name = "Segy"
uuid = "05bd159c-2902-4555-8394-afb6d27f67e8"
version = "0.1.0"
authors = ["JÃºlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]

[deps]
FieldViews = "ff5a1669-b1f2-423e-bbd7-b7fa0f7e0224"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
WrappedUnions = "325db55a-9c6c-5b90-b1a2-ec87e7a38c44"

[compat]
FieldViews = "0.3"
PrettyTables = "3.1"
StringEncodings = "0.3"
StyledStrings = "1.0"
WrappedUnions = "0.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
